### ISSUE TITLE
ppa missing?

### ISSUE THREAD

**Issue by mockdeep** [kgraefe/pidgin-extended-blist-sort#2]
The PPA archive for this plugin seems to have disappeared. Is there a new location I should be adding to get updates?

**Comment by kgraefe** [comment]
I don't use Ubuntu anymore. Therefore I was not maintaining the PPA for quite a while and finally shut it down. Sorry.

You'll have to install the plugin from source or, even better, maintain a PPA yourself. As for update notifications you may want to subscribe to the [release RSS feed](https://github.com/kgraefe/pidgin-extended-blist-sort/releases.atom) or follow [@pidgin_plugins](https://twitter.com/pidgin_plugins) on Twitter.
