### ISSUE TITLE
Some contacts aren't being correctly ordered

### ISSUE THREAD

**Issue by lmfardin** [kgraefe/pidgin-extended-blist-sort#8]
I usually order my contacts by log size on reverse (from the smallest to the largest log size). However, a few days from now I noticed that some contacts aren't being correctly ordered.
For some contacts with whom I have a log, if I right click and go to history, I see the history but not the log size at the bottom of the window.

**Comment by kgraefe** [comment]
That's an issue in Pidgin (libpurple) then. The plugin uses [purple_log_get_total_size()](https://developer.pidgin.im/doxygen/dev2.x.y/html/log_8h.html#aae78ae0a63da96e63766cd85dbb911af) to get the log size.

**Comment by lmfardin** [comment]
Should I report this at Pidgin support mailing list? 

    Em Quarta-feira, 7 de Junho de 2017 4:01, Konrad Gräfe <notifications@github.com> escreveu:
 

 That's an issue in Pidgin (libpurple) then. The plugin uses purple_log_get_total_size() to get the log size.—

**Comment by kgraefe** [comment]
Sure, go ahead. I'd appreciate if you would document their response here for others having the same issue.

P.S.: If you answer via mail, please do not cite the  previous post.
